-- Crear tabla patients
CREATE TABLE patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unity_tag TEXT UNIQUE NOT NULL,
  nombre TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Políticas de seguridad de nivel de fila (RLS) - opcional según configuración
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;

-- Permitir a todos leer/escribir si la API confía en service_role key, 
-- pero es buena práctica tener al menos:
CREATE POLICY "Enable read access for all users" ON patients FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON patients FOR INSERT WITH CHECK (auth.role() = 'authenticated' OR true);
CREATE POLICY "Enable update for authenticated users only" ON patients FOR UPDATE USING (auth.role() = 'authenticated' OR true);
CREATE POLICY "Enable delete for authenticated users only" ON patients FOR DELETE USING (auth.role() = 'authenticated' OR true);
